apiVersion: v2
name: streamworks
description: Enterprise Helm Chart for StreamWorks RAG Application
version: 1.0.0
appVersion: "1.0.0"
type: application

keywords:
  - streamworks
  - rag
  - ai
  - enterprise
  - langgraph

home: https://github.com/streamworks/streamworks-ki
sources:
  - https://github.com/streamworks/streamworks-ki

maintainers:
  - name: StreamWorks Team
    email: team@streamworks.arvato-systems.com

dependencies:
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.4.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "15.16.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled