-- Complete training_files view for backward compatibility
CREATE OR REPLACE VIEW training_files AS
SELECT 
    id::text,
    original_filename as filename,
    display_name,
    'qa' as category,
    storage_path as file_path,
    created_at as upload_date,
    file_size,
    processing_status as status,
    error_message,
    (processing_status = 'completed') as is_indexed,
    processed_at as indexed_at,
    chunk_count,
    '[]'::jsonb as chromadb_ids,
    processing_status as index_status,
    error_message as index_error,
    storage_path as processed_file_path,
    file_type as original_format,
    file_type as optimized_format,
    processing_status as conversion_status,
    error_message as conversion_error,
    COALESCE(metadata::text, '{}') as conversion_metadata,
    error_message as processing_error,
    'qa' as document_category,
    'auto' as processing_method,
    'high' as processing_quality,
    1.0 as extraction_confidence,
    'document' as source_type,
    original_filename as source_title,
    '' as source_url,
    file_type as document_type,
    '' as author,
    version,
    updated_at as last_modified,
    'normal' as priority,
    tags,
    language,
    'qa' as manual_source_category,
    display_name as description,
    created_at as upload_timestamp,
    storage_path as original_path,
    uploaded_by::text as user_id
FROM training_files_v2
WHERE is_active = true AND deleted_at IS NULL;