# Enterprise Prometheus Configuration for StreamWorks RAG Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'streamworks-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # StreamWorks Backend Metrics
  - job_name: 'streamworks-backend'
    static_configs:
      - targets: ['streamworks-backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: 'streamworks-backend'

  # StreamWorks Frontend Metrics (Nginx)
  - job_name: 'streamworks-frontend'
    static_configs:
      - targets: ['streamworks-frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database Metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['streamworks-postgres:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9104']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom RAG Pipeline Metrics
  - job_name: 'rag-pipelines'
    static_configs:
      - targets: ['streamworks-backend:8000']
    metrics_path: '/graph/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - target_label: component
        replacement: 'rag-pipeline'

  # LangGraph Workflow Metrics
  - job_name: 'langgraph-workflows'
    static_configs:
      - targets: ['streamworks-backend:8000']
    metrics_path: '/admin/langgraph/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - target_label: component
        replacement: 'langgraph-workflows'

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - streamworks-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

storage:
  tsdb:
    path: /prometheus
    retention.time: 90d
    retention.size: 50GB