"""
Streaming Query Service

Provides real-time token streaming for RAG responses using LlamaIndex.
Uses Server-Sent Events (SSE) for client communication.
"""

import asyncio
import json
from typing import AsyncGenerator, Optional, List, Dict, Any
from dataclasses import dataclass, asdict

from config import config
from .settings import LlamaIndexSettings, configure_llamaindex


@dataclass
class StreamChunk:
    """A chunk of streaming response"""
    type: str  # "token", "source", "metadata", "done", "error"
    content: str = ""
    data: Optional[Dict[str, Any]] = None


class StreamingQueryService:
    """
    Streaming Query Service for RAG
    
    Streams tokens as they are generated by the LLM for a better UX.
    Uses the existing retrieval pipeline but with streaming response.
    """
    
    RAG_SYSTEM_PROMPT = """Du bist ein hilfreicher Assistent für StreamWorks und beantwortest Fragen 
basierend auf den bereitgestellten Dokumenten. Beantworte Fragen präzise und nutze 
die Informationen aus dem Kontext. Wenn du die Antwort nicht im Kontext findest, 
sage es ehrlich.

Formatiere deine Antworten klar und strukturiert. Verwende Aufzählungen wo sinnvoll."""

    def __init__(self):
        configure_llamaindex()
        self._vector_store = None
        self._reranker = None
    
    @property
    def vector_store(self):
        if self._vector_store is None:
            from services.rag.vector_store import vector_store
            self._vector_store = vector_store
        return self._vector_store
    
    @property
    def reranker(self):
        if self._reranker is None and config.RAG_RERANK_ENABLED:
            from services.rag.reranker import CrossEncoderReranker
            self._reranker = CrossEncoderReranker(use_batch_mode=True)
        return self._reranker
    
    async def stream_query(
        self,
        query_text: str,
        top_k: int = 5,
        session_id: Optional[str] = None,
        doc_ids: List[str] = None,
    ) -> AsyncGenerator[str, None]:
        """
        Stream a RAG query response
        
        Yields SSE-formatted events:
        - event: token    -> individual tokens
        - event: source   -> source documents
        - event: metadata -> confidence, query type
        - event: done     -> completion signal
        - event: error    -> error information
        """
        try:
            # 0. Contextual Memory: Rewrite query based on history
            actual_query = query_text
            if session_id:
                try:
                    from services.chat_session_service import chat_session_service
                    
                    # Fetch history (last 10 messages)
                    session = chat_session_service.get_session(session_id)
                    if session and session.get("messages"):
                        history = session["messages"]
                        
                        # Rewrite query
                        from services.llamaindex.context_utils import enhance_query_with_history
                        rewritten_query = enhance_query_with_history(actual_query, history)
                        
                        if rewritten_query != actual_query:
                             actual_query = rewritten_query
                             # Optionally stream a status update about rewriting
                except Exception as e:
                    print(f"Failed to enhance streaming query: {e}")

            # 1. Retrieve relevant documents
            yield self._format_sse("status", {"message": "Suche relevante Dokumente..."})
            
            retrieved_chunks = await self._retrieve(actual_query, top_k, doc_ids)
            
            if not retrieved_chunks:
                yield self._format_sse("token", {"content": "Ich konnte keine relevanten Informationen in den Dokumenten finden."})
                yield self._format_sse("done", {"has_context": False})
                return
            
            # 2. Check relevance
            is_relevant = self._check_relevance(retrieved_chunks, actual_query)
            
            if not is_relevant:
                yield self._format_sse("token", {"content": "Zu dieser Frage habe ich leider keine passenden Informationen in den verfügbaren Dokumenten gefunden."})
                yield self._format_sse("done", {"has_context": False, "confidence": 0.0})
                return
            
            # 3. Apply reranking if enabled
            if self.reranker:
                yield self._format_sse("status", {"message": "Optimiere Ergebnisse..."})
                retrieved_chunks = await self._rerank(actual_query, retrieved_chunks, top_k)
            
            # 4. Stream sources first
            sources = self._extract_sources(retrieved_chunks)
            for source in sources:
                yield self._format_sse("source", source)
            
            # 5. Build context and stream LLM response
            context = self._build_context(retrieved_chunks)
            yield self._format_sse("status", {"message": "Generiere Antwort..."})
            
            # Stream tokens from LLM
            full_response = ""
            async for token in self._stream_llm_response(actual_query, context):
                full_response += token
                yield self._format_sse("token", {"content": token})
            
            # 6. Send final metadata
            confidence = self._calculate_confidence(retrieved_chunks)
            query_type = self._classify_query(actual_query)
            
            yield self._format_sse("done", {
                "has_context": True,
                "chunks_found": len(retrieved_chunks),
                "confidence": confidence,
                "query_type": query_type,
                "full_response": full_response,
            })
            
        except Exception as e:
            yield self._format_sse("error", {"message": str(e)})
    
    async def _retrieve(
        self,
        query_text: str,
        top_k: int,
        doc_ids: List[str] = None,
    ) -> List[Dict[str, Any]]:
        """Retrieve documents (async wrapper for sync operation)"""
        loop = asyncio.get_event_loop()
        
        access_filter = None
        if doc_ids:
            access_filter = {"parent_doc_ids": doc_ids}
        
        # Run in thread pool to not block
        def do_search():
            return self.vector_store.search(
                query=query_text,
                limit=top_k * 3 if config.RAG_RERANK_ENABLED else top_k,
                score_threshold=0.2,
                access_filter=access_filter,
            )
        
        return await loop.run_in_executor(None, do_search)
    
    async def _rerank(
        self,
        query_text: str,
        chunks: List[Dict[str, Any]],
        top_k: int,
    ) -> List[Dict[str, Any]]:
        """Rerank results (async wrapper)"""
        loop = asyncio.get_event_loop()
        
        def do_rerank():
            ranked = self.reranker.rerank(
                query=query_text,
                results=chunks,
                top_k=top_k,
            )
            return [
                {
                    "doc_id": r.doc_id,
                    "content": r.content,
                    "filename": r.filename,
                    "score": r.rerank_score,
                    "metadata": r.metadata,
                }
                for r in ranked
            ]
        
        return await loop.run_in_executor(None, do_rerank)
    
    async def _stream_llm_response(
        self,
        query: str,
        context: str,
    ) -> AsyncGenerator[str, None]:
        """Stream tokens from LLM"""
        import openai
        
        client = openai.AsyncOpenAI(api_key=config.OPENAI_API_KEY)
        
        messages = [
            {"role": "system", "content": self.RAG_SYSTEM_PROMPT},
            {"role": "user", "content": f"""Basierend auf folgendem Kontext, beantworte die Frage.

KONTEXT:
{context}

FRAGE: {query}

ANTWORT:"""},
        ]
        
        # Use streaming
        stream = await client.chat.completions.create(
            model=config.LLM_MODEL,
            messages=messages,
            stream=True,
            temperature=0.3,
        )
        
        async for chunk in stream:
            if chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content
    
    def _build_context(self, chunks: List[Dict[str, Any]]) -> str:
        """Build context from retrieved chunks"""
        context_parts = []
        for i, chunk in enumerate(chunks):
            filename = chunk.get("filename") or chunk.get("metadata", {}).get("filename", "Unbekannt")
            content = chunk.get("content", "")
            context_parts.append(f"[Quelle {i+1}: {filename}]:\n{content}")
        return "\n\n---\n\n".join(context_parts)
    
    def _extract_sources(self, chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Extract source information"""
        sources = []
        for chunk in chunks:
            meta = chunk.get("metadata", {})
            content = chunk.get("content", "")
            sources.append({
                "doc_id": meta.get("parent_doc_id") or chunk.get("doc_id"),
                "filename": chunk.get("filename") or meta.get("filename", "Unbekannt"),
                "content": content[:300] + "..." if len(content) > 300 else content,
                "score": round(chunk.get("score", 0), 4),
            })
        return sources
    
    def _check_relevance(self, chunks: List[Dict[str, Any]], query: str) -> bool:
        """Check if results are relevant"""
        import re
        
        query_lower = query.lower()
        
        # Check for external tech not in docs
        external_tech = [
            "kubernetes", "k8s", "docker", "aws", "azure", "gcp",
            "terraform", "ansible", "jenkins", "kafka", "elasticsearch"
        ]
        
        if any(tech in query_lower for tech in external_tech):
            content = " ".join(c.get("content", "").lower() for c in chunks[:3])
            for tech in external_tech:
                if tech in query_lower and tech not in content:
                    return False
        
        return True
    
    def _calculate_confidence(self, chunks: List[Dict[str, Any]]) -> float:
        """Calculate confidence score"""
        if not chunks:
            return 0.0
        scores = [c.get("score", 0) for c in chunks]
        return round(min(sum(scores) / len(scores) * 1.2, 1.0), 3)
    
    def _classify_query(self, query: str) -> str:
        """Classify query type"""
        query_lower = query.lower()
        if any(w in query_lower for w in ["wie", "how", "anleitung"]):
            return "how_to"
        elif any(w in query_lower for w in ["config", "konfigur"]):
            return "configuration"
        elif any(w in query_lower for w in ["fehler", "error"]):
            return "troubleshooting"
        return "general"
    
    def _format_sse(self, event_type: str, data: Dict[str, Any]) -> str:
        """Format as Server-Sent Event"""
        return f"event: {event_type}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


# Singleton
_streaming_service: Optional[StreamingQueryService] = None


def get_streaming_service() -> StreamingQueryService:
    """Get singleton streaming service"""
    global _streaming_service
    if _streaming_service is None:
        _streaming_service = StreamingQueryService()
    return _streaming_service
