/**
 * Parameter Overview Component for LangExtract
 * Shows extracted stream and job parameters with modern UI
 */

'use client'

import React from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  CheckCircle,
  AlertCircle,
  Clock,
  Settings,
  Zap,
  Copy,
  Sparkles,
  Edit3,
  Target,
  Info,
  ArrowRightLeft,
  Database,
  Terminal
} from 'lucide-react'
import { toast } from 'sonner'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

// ================================
// TYPES
// ================================

interface LangExtractSession {
  session_id: string
  job_type?: string
  stream_name: string
  completion_percentage: number
  created_at: string
  last_activity: string
}

interface ParameterOverviewProps {
  streamParameters: Record<string, any>
  jobParameters: Record<string, any>
  completionPercentage: number
  criticalMissing: string[]
  currentSessionId: string | null
  sessions: LangExtractSession[]
  onParameterEdit?: (parameterName: string, currentValue: any) => void
  className?: string
}

interface ParameterItem {
  key: string
  value: any
  label: string
  status: 'extracted' | 'missing' | 'critical' | 'auto-generated'
  category: 'stream' | 'job'
  description: string
}

// ================================
// JOB TYPE DEFINITIONS
// ================================

interface JobTypeDefinition {
  id: string
  title: string
  description: string
  icon: React.ComponentType<any>
  color: string
  keywords: string[]
}

const JOB_TYPE_DEFINITIONS: JobTypeDefinition[] = [
  {
    id: 'FILE_TRANSFER',
    title: 'Dateiübertragung',
    description: 'Transfer zwischen Systemen und Servern',
    icon: ArrowRightLeft,
    color: 'emerald',
    keywords: ['datentransfer', 'übertragung', 'server', 'agent', 'sync']
  },
  {
    id: 'SAP',
    title: 'SAP Export',
    description: 'SAP Reports und System-Exporte',
    icon: Database,
    color: 'blue',
    keywords: ['sap', 'export', 'system', 'report', 'pa1', 'gt123']
  },
  {
    id: 'STANDARD',
    title: 'Script-Job',
    description: 'Allgemeine Verarbeitungs-Scripts',
    icon: Terminal,
    color: 'orange',
    keywords: ['script', 'command', 'programm', 'process', 'workflow']
  }
]

// ================================
// PARAMETER DEFINITIONS
// ================================

// Schema v2.0 PROTOTYP: Stream Parameter Definitions
interface ParameterDefinition {
  label: string
  description: string
  required?: boolean
  autoGenerated?: boolean
  conditional?: string
}

const STREAM_PARAMETER_DEFINITIONS: Record<string, ParameterDefinition> = {
  StreamName: { label: 'Stream Name', description: 'Eindeutiger Name für den Stream', required: true },
  MaxStreamRuns: { label: 'Max. Läufe', description: 'Maximale parallele Ausführungen (1, 3, 5, 10, 20)', required: false },
  SchedulingRequiredFlag: { label: 'Zeitplanung', description: 'Zeitgesteuert oder manuell ausführen', required: false },
  StartTime: { label: 'Startzeit', description: 'Startzeit im Format HH:MM (nur bei Zeitplanung)', required: false, conditional: 'SchedulingRequiredFlag' }
}

// Schema v2.0 PROTOTYP: Auto-Generated Parameters
const AUTO_GENERATED_PARAMETER_DEFINITIONS: Record<string, ParameterDefinition> = {
  JobCategory: { label: '✨ Job-Kategorie', description: 'Automatisch erkannt', autoGenerated: true },
  JobType: { label: '✨ Script-Typ', description: 'Automatisch erkannt: Windows oder Unix', autoGenerated: true }
}

// Schema v2.0 PROTOTYP: Job-specific parameters
const JOB_SPECIFIC_PARAMETER_DEFINITIONS: Record<string, Record<string, ParameterDefinition>> = {
  SAP: {
    system: { label: 'SAP System', description: 'SAP-System mit Mandant (PA1_100, GT123_PRD, PT1_100)', required: true },
    report: { label: 'Report/Programm', description: 'SAP Report oder Programm-Name (ZTV_EXPORT_001, RSUSR003)', required: false },
    variant: { label: 'Report-Variante', description: 'Report-Variante (DAILY_EXPORT, MONTHLY_REPORT, STANDARD)', required: false }
  },

  FILE_TRANSFER: {
    source_agent: { label: 'Quell-Agent', description: 'Von welchem System/Agent sollen Dateien übertragen werden', required: true },
    target_agent: { label: 'Ziel-Agent', description: 'Zu welchem System/Agent sollen Dateien übertragen werden', required: true },
    source_path: { label: 'Quell-Pfad', description: 'Quell-Dateipfad oder -pattern (*.csv, /data/export/)', required: false },
    target_path: { label: 'Ziel-Pfad', description: 'Ziel-Dateipfad oder -verzeichnis (/backup/import/, D:\\Incoming\\)', required: false }
  },

  STANDARD: {
    MainScript: { label: 'Script/Command', description: 'Script-Inhalt oder Command der ausgeführt werden soll', required: true }
  }
}

// Schema v2.0 PROTOTYP: Get parameters based on job type detection
const getJobParameterDefinitions = (jobType: string | null): Record<string, ParameterDefinition> => {
  // Always show auto-generated parameters
  let definitions: Record<string, ParameterDefinition> = { ...AUTO_GENERATED_PARAMETER_DEFINITIONS }

  // Add job-specific parameters if job type is detected
  if (jobType) {
    const normalizedJobType = jobType === 'FileTransfer' ? 'FILE_TRANSFER' : jobType

    if (JOB_SPECIFIC_PARAMETER_DEFINITIONS[normalizedJobType]) {
      definitions = {
        ...definitions,
        ...JOB_SPECIFIC_PARAMETER_DEFINITIONS[normalizedJobType]
      }
    }
  }

  return definitions
}

// ================================
// COMPONENT
// ================================

export default function ParameterOverview({
  streamParameters = {},
  jobParameters = {},
  completionPercentage,
  criticalMissing = [],
  currentSessionId,
  sessions,
  onParameterEdit,
  className = ''
}: ParameterOverviewProps) {

  // 🧹 PHASE 3 FIX: Enhanced parameter filtering and job type detection
  const cleanedStreamParameters = filterParameterArtifacts(streamParameters)
  const cleanedJobParameters = filterParameterArtifacts(jobParameters)

  // ✅ SUPER SIMPLE: Get job type directly from Backend Session
  const currentSession = sessions.find(s => s.session_id === currentSessionId)
  const currentJobType = currentSession?.job_type || null

  const relevantJobParameterDefinitions = getJobParameterDefinitions(currentJobType)

  // Check if we have a job type detected
  const hasJobTypeDetected = currentJobType && currentJobType.trim() !== ''

  console.log('🔍 LangExtract ParameterOverview Debug:', {
    currentSessionId,
    currentSession,
    backendJobType: currentSession?.job_type,
    currentJobType,
    hasJobTypeDetected,
    originalStreamParams: Object.keys(streamParameters),
    originalJobParams: Object.keys(jobParameters)
  })

  // Build parameter display items
  const allParameters: ParameterItem[] = []

  // Stream parameters (always shown) - using cleaned parameters
  Object.entries(STREAM_PARAMETER_DEFINITIONS).forEach(([key, def]) => {
    const hasValue = cleanedStreamParameters.hasOwnProperty(key) &&
                    cleanedStreamParameters[key] !== null &&
                    cleanedStreamParameters[key] !== undefined &&
                    cleanedStreamParameters[key] !== ''

    allParameters.push({
      key,
      value: cleanedStreamParameters[key],
      label: def.label,
      status: criticalMissing.includes(key) ? 'critical' : (hasValue ? 'extracted' : 'missing'),
      category: 'stream',
      description: def.description
    })
  })

  // Job parameters (filtered by job type) - using cleaned parameters
  Object.entries(relevantJobParameterDefinitions).forEach(([key, def]) => {
    const hasValue = cleanedJobParameters.hasOwnProperty(key) &&
                    cleanedJobParameters[key] !== null &&
                    cleanedJobParameters[key] !== undefined &&
                    cleanedJobParameters[key] !== ''

    // Determine status based on whether it's auto-generated
    let status: 'extracted' | 'missing' | 'critical' | 'auto-generated'
    if (def.autoGenerated) {
      status = 'auto-generated'
    } else if (criticalMissing.includes(key)) {
      status = 'critical'
    } else if (hasValue) {
      status = 'extracted'
    } else if (def.required) {
      status = 'missing'
    } else {
      status = 'missing' // Optional parameters shown as missing until filled
    }

    allParameters.push({
      key,
      value: cleanedJobParameters[key],
      label: def.label,
      status,
      category: 'job',
      description: def.description
    })
  })

  const streamParams = allParameters.filter(p => p.category === 'stream')
  const jobParams = allParameters.filter(p => p.category === 'job')

  // ✨ Filter job parameters based on detected job type
  const getJobTypeSpecificParameters = (jobType: string | null, allJobParams: ParameterItem[]): ParameterItem[] => {
    if (!jobType) return allJobParams

    // Define job type specific parameter patterns
    const parameterPatterns = {
      'FILE_TRANSFER': ['source_agent', 'target_agent', 'source_path', 'target_path'],
      'SAP': ['system', 'report', 'variant'],
      'STANDARD': ['MainScript', 'script', 'command', 'Command']
    }

    const patterns = parameterPatterns[jobType as keyof typeof parameterPatterns] || []

    // Filter parameters that match the job type patterns
    const relevantParams = allJobParams.filter(param =>
      patterns.some(pattern =>
        param.key.toLowerCase().includes(pattern.toLowerCase()) ||
        param.label.toLowerCase().includes(pattern.toLowerCase())
      )
    )

    // Return only relevant params - no fallback, only best solution
    return relevantParams
  }

  // ✨ Get job-type specific parameters from both stream and job parameters
  const allParamsForFiltering = [...streamParams, ...jobParams]
  const jobTypeSpecificParams = hasJobTypeDetected ?
    getJobTypeSpecificParameters(currentJobType, allParamsForFiltering) :
    jobParams

  const extractedCount = allParameters.filter(p => p.status === 'extracted' || p.status === 'auto-generated').length
  const totalCount = allParameters.length
  const criticalCount = allParameters.filter(p => p.status === 'critical').length
  const autoGeneratedCount = allParameters.filter(p => p.status === 'auto-generated').length

  const handleCopyValue = async (value: any) => {
    try {
      await navigator.clipboard.writeText(String(value))
      toast.success('Wert kopiert!')
    } catch (error) {
      toast.error('Kopieren fehlgeschlagen')
    }
  }

  const handleParameterEdit = (param: ParameterItem) => {
    onParameterEdit?.(param.key, param.value)
  }

  const renderJobTypeDisplay = () => {
    if (!hasJobTypeDetected) {
      // Zustand 1: Noch kein Job-Typ erkannt - zeige alle verfügbaren Typen
      return (
        <motion.div
          className="mb-6"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="overflow-hidden">
            {/* Job-Typ Header */}
            <div className="bg-gray-50 border-b border-gray-100 p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-gray-100 rounded-lg flex items-center justify-center">
                    <Target className="w-4 h-4 text-gray-600" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">Job-Typ</h4>
                    <p className="text-sm text-gray-600">Wird automatisch aus dem Chat erkannt</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Verfügbare Job-Typen */}
            <div className="p-4">
              <div className="grid grid-cols-1 gap-3">
                {JOB_TYPE_DEFINITIONS.map((jobType) => {
                  const IconComponent = jobType.icon
                  return (
                    <motion.div
                      key={jobType.id}
                      className="relative overflow-hidden rounded-lg border-2 border-gray-200 bg-gray-50 opacity-60"
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 0.6, x: 0 }}
                      transition={{ delay: 0.1 }}
                    >
                      <div className="p-3">
                        <div className="flex items-center gap-3">
                          <div className={`w-10 h-10 bg-${jobType.color}-100 rounded-lg flex items-center justify-center flex-shrink-0`}>
                            <IconComponent className={`w-5 h-5 text-${jobType.color}-600`} />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium text-gray-700">
                              {jobType.title}
                            </div>
                            <p className="text-sm text-gray-500 mt-1">
                              {jobType.description}
                            </p>
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  )
                })}
              </div>
            </div>
          </Card>
        </motion.div>
      )
    } else {
      // Zustand 2 & 3: Job-Typ erkannt - zeige aktiven Job-Typ
      const detectedJobType = JOB_TYPE_DEFINITIONS.find(jt => jt.id === currentJobType)!

      const IconComponent = detectedJobType.icon
      const jobParametersCount = jobTypeSpecificParams.filter(p => p.status === 'extracted' || p.status === 'auto-generated').length
      const totalJobParameters = jobTypeSpecificParams.length

      return (
        <motion.div
          className="mb-6"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="overflow-hidden">
            {/* Erkannter Job-Typ Header */}
            <div className={`bg-${detectedJobType.color}-50 border-b border-${detectedJobType.color}-100 p-4`}>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 bg-${detectedJobType.color}-100 rounded-lg flex items-center justify-center`}>
                    <IconComponent className={`w-4 h-4 text-${detectedJobType.color}-600`} />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">
                      {detectedJobType.title} Job-Konfiguration
                    </h4>
                    <p className="text-sm text-gray-600">
                      {jobParametersCount}/{totalJobParameters} Parameter
                    </p>
                  </div>
                </div>
                <Badge className={`bg-${detectedJobType.color}-100 text-${detectedJobType.color}-700`}>
                  ✓ Erkannt
                </Badge>
              </div>
            </div>

            {/* Job Parameter */}
            <div className="p-4 space-y-3">
              <AnimatePresence>
                {jobTypeSpecificParams.map((param, index) => (
                  <motion.div
                    key={param.key}
                    className={`group relative overflow-hidden rounded-lg border-2 transition-all duration-200 ${
                      param.status === 'extracted'
                        ? 'border-emerald-200 bg-emerald-50/50 hover:bg-emerald-50'
                        : param.status === 'auto-generated'
                        ? 'border-blue-200 bg-gradient-to-r from-blue-50 to-purple-50 hover:from-blue-100 hover:to-purple-100'
                        : param.status === 'critical'
                        ? 'border-red-200 bg-red-50/50 hover:bg-red-50'
                        : 'border-gray-200 bg-gray-50/50 hover:bg-gray-50'
                    }`}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    title={param.description}
                  >
                    <div className="p-4">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          {param.status === 'extracted' ? (
                            <CheckCircle className="w-5 h-5 text-emerald-600 flex-shrink-0" />
                          ) : param.status === 'auto-generated' ? (
                            <Sparkles className="w-5 h-5 text-blue-600 flex-shrink-0" />
                          ) : param.status === 'critical' ? (
                            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0" />
                          ) : (
                            <Clock className="w-5 h-5 text-gray-400 flex-shrink-0" />
                          )}

                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <span className="font-medium text-gray-900 truncate">
                                {param.label}
                              </span>
                              {param.status === 'critical' && (
                                <Badge variant="destructive" className="text-xs">
                                  Kritisch
                                </Badge>
                              )}
                              {param.status === 'auto-generated' && (
                                <Badge className="text-xs bg-blue-100 text-blue-700">
                                  ✨ KI
                                </Badge>
                              )}
                            </div>
                            <p className="text-xs text-gray-500 mt-1">
                              {param.description}
                            </p>
                          </div>
                        </div>

                        {/* Value and Actions */}
                        <div className="flex items-center gap-2 ml-4">
                          {param.status === 'extracted' || param.status === 'auto-generated' ? (
                            <div className="flex items-center gap-2">
                              <code className={`text-sm font-mono px-2 py-1 rounded border max-w-32 truncate ${
                                param.status === 'auto-generated'
                                  ? 'text-blue-700 bg-blue-50 border-blue-200 font-medium'
                                  : 'text-gray-700 bg-white'
                              }`} title={String(param.value)}>
                                {formatParameterValue(param.value)}
                              </code>
                              <div className="flex gap-1">
                                <button
                                  onClick={() => handleCopyValue(param.value)}
                                  className="opacity-0 group-hover:opacity-100 p-1.5 hover:bg-white rounded transition-all"
                                  title="Kopieren"
                                >
                                  <Copy className="w-4 h-4 text-gray-500" />
                                </button>
                                {onParameterEdit && (
                                  <button
                                    onClick={() => handleParameterEdit(param)}
                                    className="opacity-0 group-hover:opacity-100 p-1.5 hover:bg-white rounded transition-all"
                                    title="Bearbeiten"
                                  >
                                    <Edit3 className="w-4 h-4 text-gray-500" />
                                  </button>
                                )}
                              </div>
                            </div>
                          ) : (
                            <span className="text-sm text-gray-400 px-3 py-1 bg-white rounded border">
                              {param.status === 'critical' ? 'Fehlt (kritisch)' : 'Nicht gesetzt'}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </Card>
        </motion.div>
      )
    }
  }

  const renderParameterGroup = (
    title: string,
    parameters: ParameterItem[],
    icon: React.ComponentType<any>,
    color: string
  ) => {
    const Icon = icon
    const extractedInGroup = parameters.filter(p => p.status === 'extracted' || p.status === 'auto-generated').length
    const criticalInGroup = parameters.filter(p => p.status === 'critical').length

    return (
      <motion.div
        className="mb-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Card className="overflow-hidden">
          {/* Group Header */}
          <div className={`bg-${color}-50 border-b border-${color}-100 p-4`}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={`w-8 h-8 bg-${color}-100 rounded-lg flex items-center justify-center`}>
                  <Icon className={`w-4 h-4 text-${color}-600`} />
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900">{title}</h4>
                  <p className="text-sm text-gray-600">
                    {extractedInGroup}/{parameters.length} Parameter
                  </p>
                </div>
              </div>
              <div className="flex gap-2">
                {criticalInGroup > 0 && (
                  <Badge variant="destructive" className="text-xs">
                    {criticalInGroup} kritisch
                  </Badge>
                )}
              </div>
            </div>
          </div>

          {/* Parameters */}
          <div className="p-4 space-y-3">
            <AnimatePresence>
              {parameters.map((param, index) => (
                <motion.div
                  key={param.key}
                  className={`group relative overflow-hidden rounded-lg border-2 transition-all duration-200 ${
                    param.status === 'extracted'
                      ? 'border-emerald-200 bg-emerald-50/50 hover:bg-emerald-50'
                      : param.status === 'auto-generated'
                      ? 'border-blue-200 bg-gradient-to-r from-blue-50 to-purple-50 hover:from-blue-100 hover:to-purple-100'
                      : param.status === 'critical'
                      ? 'border-red-200 bg-red-50/50 hover:bg-red-50'
                      : 'border-gray-200 bg-gray-50/50 hover:bg-gray-50'
                  }`}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.05 }}
                  title={param.description}
                >
                  <div className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3 flex-1 min-w-0">
                        {param.status === 'extracted' ? (
                          <CheckCircle className="w-5 h-5 text-emerald-600 flex-shrink-0" />
                        ) : param.status === 'auto-generated' ? (
                          <Sparkles className="w-5 h-5 text-blue-600 flex-shrink-0" />
                        ) : param.status === 'critical' ? (
                          <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0" />
                        ) : (
                          <Clock className="w-5 h-5 text-gray-400 flex-shrink-0" />
                        )}

                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="font-medium text-gray-900 truncate">
                              {param.label}
                            </span>
                            {param.status === 'critical' && (
                              <Badge variant="destructive" className="text-xs">
                                Kritisch
                              </Badge>
                            )}
                            {param.status === 'auto-generated' && (
                              <Badge className="text-xs bg-blue-100 text-blue-700">
                                ✨ KI
                              </Badge>
                            )}
                          </div>
                          <p className="text-xs text-gray-500 mt-1">
                            {param.description}
                          </p>
                        </div>
                      </div>

                      {/* Value and Actions */}
                      <div className="flex items-center gap-2 ml-4">
                        {param.status === 'extracted' || param.status === 'auto-generated' ? (
                          <div className="flex items-center gap-2">
                            <code className={`text-sm font-mono px-2 py-1 rounded border max-w-32 truncate ${
                              param.status === 'auto-generated'
                                ? 'text-blue-700 bg-blue-50 border-blue-200 font-medium'
                                : 'text-gray-700 bg-white'
                            }`} title={String(param.value)}>
                              {formatParameterValue(param.value)}
                            </code>
                            <div className="flex gap-1">
                              <button
                                onClick={() => handleCopyValue(param.value)}
                                className="opacity-0 group-hover:opacity-100 p-1.5 hover:bg-white rounded transition-all"
                                title="Kopieren"
                              >
                                <Copy className="w-4 h-4 text-gray-500" />
                              </button>
                              {onParameterEdit && (
                                <button
                                  onClick={() => handleParameterEdit(param)}
                                  className="opacity-0 group-hover:opacity-100 p-1.5 hover:bg-white rounded transition-all"
                                  title="Bearbeiten"
                                >
                                  <Edit3 className="w-4 h-4 text-gray-500" />
                                </button>
                              )}
                            </div>
                          </div>
                        ) : (
                          <span className="text-sm text-gray-400 px-3 py-1 bg-white rounded border">
                            {param.status === 'critical' ? 'Fehlt (kritisch)' : 'Nicht gesetzt'}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </Card>
      </motion.div>
    )
  }

  return (
    <motion.div
      className={`h-full w-full flex flex-col ${className}`}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3, ease: 'easeInOut' }}
    >
      {/* Critical Missing Alert */}
      {criticalCount > 0 && (
        <motion.div
          className="m-6 p-3 bg-red-50 border border-red-200 rounded-lg"
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-red-600" />
            <span className="text-sm font-medium text-red-900">
              {criticalCount} kritische Parameter fehlen
            </span>
          </div>
        </motion.div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6">
        {/* Stream Parameters */}
        {renderParameterGroup(
          'Stream-Konfiguration',
          streamParams,
          Settings,
          'blue'
        )}

        {/* Job-Typ Anzeige - Ersetzt alte Job Parameters Logik */}
        {renderJobTypeDisplay()}

        {/* Empty State */}
        {extractedCount === 0 && (
          <div className="text-center py-12">
            <Target className="w-12 h-12 mx-auto text-gray-400 mb-4" />
            <p className="text-gray-500">
              Noch keine Parameter extrahiert
            </p>
            <p className="text-gray-400 text-sm mt-1">
              Parameter werden während der Unterhaltung automatisch erkannt
            </p>
          </div>
        )}
      </div>

      {/* Footer Summary */}
      <div className="bg-gray-50 border-t border-gray-200 p-4">
        <div className="flex justify-center gap-6 text-sm">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-emerald-500 rounded-full"></div>
            <span className="text-gray-600">{extractedCount} extrahiert</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-red-500 rounded-full"></div>
            <span className="text-gray-600">{criticalCount} kritisch</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-gray-400 rounded-full"></div>
            <span className="text-gray-600">{totalCount - extractedCount - criticalCount} ausstehend</span>
          </div>
        </div>
      </div>
    </motion.div>
  )
}

/**
 * 🧹 PHASE 3 FIX: Filter out LangExtract artifacts from UI parameters
 */
function filterParameterArtifacts(parameters: Record<string, any>): Record<string, any> {
  const filtered: Record<string, any> = {}

  // Technical fields that should never be displayed in UI
  const technicalFields = new Set([
    'extractions',
    'text',
    '_document_id',
    'extraction_class',
    'extraction_text',
    'confidence',
    'highlighted_ranges',
    'source_grounding',
    'metadata',
    '__dict__',
    '__class__',
    'api_calls_made',
    'extraction_duration',
    'warnings',
    'extraction_errors',
    'processing_time'
  ])

  for (const [key, value] of Object.entries(parameters)) {
    // Skip technical fields
    if (technicalFields.has(key.toLowerCase())) {
      continue
    }

    // Skip empty, null, or undefined values
    if (value === null || value === undefined || value === '') {
      continue
    }

    // Skip object references and technical artifacts
    if (typeof value === 'string') {
      if (value.toLowerCase().includes('[object') ||
          value.toLowerCase().includes('undefined') ||
          value.toLowerCase() === 'null') {
        continue
      }
    }

    // Only include clean, meaningful parameters
    filtered[key] = value
  }

  return filtered
}

/**
 * Format parameter values for display, handling edge cases
 */
function formatParameterValue(value: any): string {
  if (value === null || value === undefined) {
    return 'null'
  }

  if (typeof value === 'string') {
    // Truncate very long values
    if (value.length > 50) {
      return value.substring(0, 47) + '...'
    }
    return value
  }

  if (typeof value === 'boolean') {
    return value ? 'true' : 'false'
  }

  if (typeof value === 'number') {
    return value.toString()
  }

  // For objects, arrays, etc.
  try {
    const str = JSON.stringify(value)
    if (str.length > 50) {
      return str.substring(0, 47) + '...'
    }
    return str
  } catch {
    return String(value)
  }
}